import Link from 'next/link';
import { ArrowUpRight, ArrowLeft, Check, Coffee, Pencil, Map, Sun } from 'lucide-react';
import { experiences } from '@/components/ExperienceCards';
import { instagram } from '@/components/SiteChrome';
import { InquiryForm } from '@/components/InquiryForm';
import { articles } from '@/lib/articles';
const details = {
 stay: {intro:'Make room for a slower rhythm.',body:'An apartment stay with an artist’s spirit. A place to unpack, pause, and make yourself at home between your adventures.',items:['An apartment to call your own','Artful spaces and quiet corners','Time to explore at your own pace'],heading:'Your next chapter starts here.',note:'Tell us your preferred dates and group size. We’ll help you find out about availability, rates, and the apartment before you book.'},
 cafe: {intro:'A table for your appetite and imagination.',body:'Coffee, conversation, and a little creative freedom. Bring your sketchbook, pick up a pencil, or simply enjoy watching a blank page become something new.',items:['A welcoming space to draw freely','Food, drinks, and unhurried moments','Everyone welcome, whatever your skill'],heading:'Nothing on your page? That’s a start.',note:'There’s no right way to create. Draw your cup, sketch a friend, or let your pencil wander. You’re welcome to make a little art here.'},
 walks: {intro:'See the everyday a little differently.',body:'A walk becomes a story when you take the time to look. Discover sketchwalks, creative wanderings, and notes from the streets that inspire us.',items:['Sketchwalks and creative explorations','Stories from the places we wander','Curiosity over experience, always'],heading:'Notes from the wandering.',note:'A growing journal of small discoveries, fresh perspectives, and things worth stopping for.'}
};
export function ExperiencePage({type}:{type:keyof typeof details}){const e=experiences.find(e=>e.slug===type)!;const d=details[type];const Icon=type==='stay'?Sun:type==='cafe'?Coffee:Map;return <main id="main"><section className={`detail-hero ${e.color}`}><div><Link className="back-link" href="/"><ArrowLeft size={16}/> Back to the nest</Link><span className="eyebrow">{e.number} / ARTNEST {e.name.toUpperCase()}</span><h1>{e.title}</h1><p>{d.intro}</p><a className="button primary" href={type==='stay'?'#enquire':type==='walks'?'#journal':'#create'}>{type==='stay'?'Enquire about a stay':type==='cafe'?'Come for the creativity':'Explore the journal'}<ArrowUpRight size={18}/></a></div><div className="detail-image"><img src={e.image} alt={e.alt}/><span className="image-sticker">{type==='stay'?'stay a little longer':type==='cafe'?'a coffee & a little art':'take a closer look'} ✳</span></div></section><section className="detail-intro section"><div><span className="eyebrow">{e.tag}</span><h2>{d.intro}</h2></div><div><p>{d.body}</p><ul className="feature-list">{d.items.map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul></div></section><section id={type==='stay'?'enquire':type==='walks'?'journal':'create'} className="detail-content section"><div className="section-heading"><div><Icon className="section-icon"/><h2>{d.heading}</h2></div><p>{d.note}</p></div>{type==='stay'?<InquiryForm/>:type==='walks'?<div className="journal-grid">{articles.map(a=><Link key={a.slug} href={`/walks/${a.slug}`} className="journal-card"><span className="eyebrow">{a.category} · {a.readTime}</span><h3>{a.title}</h3><p>{a.description}</p><span className="text-link">Read the story <ArrowUpRight size={18}/></span></Link>)}</div>:<div className="cafe-panels"><article><Coffee size={30}/><h3>Something to savour.</h3><p>Make time for food and a drink, then linger over a conversation. Get in touch for the current menu and visiting information.</p><a className="text-link" href={instagram} target="_blank" rel="noreferrer">Ask about the cafe <ArrowUpRight size={18}/></a></article><article><Pencil size={30}/><h3>Something to create.</h3><p>Bring your own materials and let your ideas find their way onto the page. A little doodle counts. So does a masterpiece.</p><a className="text-link" href={instagram} target="_blank" rel="noreferrer">Plan a creative visit <ArrowUpRight size={18}/></a></article></div>}</section><div className="cross-links section"><span className="eyebrow">THERE’S MORE TO THE NEST</span>{experiences.filter(x=>x.slug!==type).map(x=><Link href={`/${x.slug}`} key={x.slug}>Explore {x.name}<ArrowUpRight size={23}/></Link>)}</div></main>}
